config/routes.rb
BenHarris::Application.routes.draw do
  get "home/about"

  get "home/blog"

  get "home/works"

  get "home/services"

  get "home/index"

  root :to => "home#index"

  match '/blog' => 'home#blog', :as => 'blog'
  match '/contact' => 'home#contact', :as => 'contact'
  match '/resume' => 'home#resume', :as => 'resume'
  match '/portfolio' => 'home#portfolio', :as => 'portfolio'
  match '/home' => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def contact
  end

  def blog
  end

  def portfolio
  end

  def resume
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog.html.haml
- content_for :title do
	Blog

app/views/home/contact.html.haml
- content_for :title do
	Contact

app/views/home/index.html.haml
- content_for :title do
  Benjamin Harris

.content
  .columnLeft
    .roundHeader
      %p introduction

    %p
      Im Benjamin, a designer who is very passionate about finding creative and unique solutions to everyday needs. 
      My background is in video production. The art of telling a story through both visual and audio elements is where my passions lay. 
      I am a do it all man, who enjoys every step of a project from concept to completion. So if you find yourself in need of a someone with my talents, please email me.

    %p.right
      \- Benjamin Harris
  .columnMiddle
    .roundHeader
      %p featured work
    %object{:type => 'application/x-shockwave-flash', :width => '325', :height => '240', :data => 'http://vimeo.com/hubnut/?user_id=user5477458&color=464C5B&background=E0E0E0&fullscreen=1&slideshow=1&stream=uploaded_videos&id&server=vimeo.com'}
      %param{:name => 'quality', :value => 'best'}
      %param{:name => 'allowfullscreen', :value => 'true'}
      %param{:name => 'allowscriptaccess', :value => 'always'}
      %param{:name => 'movie', :value => 'http://vimeo.com/hubnut/?user_id=user5477458&color=464C5B&background=E0E0E0&fullscreen=1&slideshow=1&stream=uploaded_videos&id&server=vimeo.com'}
  .columnRight
    .roundHeader
      %p skill set
    = image_tag('/images/BenHarrisGraph.png')

  .clear

app/views/home/portfolio.html.haml
- content_for :title do
	Portfolio

app/views/home/resume.html.haml
- content_for :title do
	Resume

app/views/layouts/_footer.html.haml
.footer
  .footer_container
    .left
      .icon_row
        = image_tag('/images/facebook-icon.png', :class => 'icon')
        = image_tag('/images/vimeo-icon.png', :class => 'icon')
        = image_tag('/images/linkedIn_icon.png', :class => 'icon')
    .right
      .contact_info
        %font.text_large benjamin.harris123@gmail.com
        %br
        %font.text_large 970.396.7316
  
  .clear

.postFooter
  .copyright &copy;2011 Benjamin Harris Creative

app/views/layouts/_header.html.haml
.header
  .header_container
    .logo= link_to image_tag('/images/BenHarrisLogo.png'), root_path
    .menu_container
      %ul.menu
        %li= link_to 'portfolio', portfolio_path
        %li= link_to 'resume', resume_path
        %li= link_to 'blog', blog_path
        %li= link_to 'contact', contact_path
.clear

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield :title
    = stylesheet_link_tag 'application'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    = render :partial => 'layouts/header'
    = yield
    .clear
    = render :partial => 'layouts/footer'